### ISSUE TITLE
Feat: color scheme / design

### ISSUE THREAD

**Issue by hannah-gk** [Lammer-FH/boutique-hotel-technikum-2023-gruppe-b-1#16]

**Comment by pa22l007** [comment]
Paar Sachen für Styling:
- Hab ein flottes Logo gebastelt
![logo](https://github.com/Lammer-FH/boutique-hotel-technikum-2023-gruppe-b-1/assets/144059533/252bb2c6-4e71-496b-a4bb-6c73aaabf477)

- Eigene Schriftarten eingeben: Können uns was bei Google Fonts raussuchen. Hier kann man sich paar Font-Paare anschauen: <https://femmebot.github.io/google-type/>
- Default Bootstrap Farben anpassen: Können wir mit CSS Variablen machen. Docu dazu hier: <https://getbootstrap.com/docs/5.2/customize/css-variables/>

**Comment by pa22l007** [comment]
Logo ist nun ein anderes
![image](https://github.com/Lammer-FH/boutique-hotel-technikum-2023-gruppe-b-1/assets/144059533/89201465-012f-4602-a1e7-6fefd75c886c)
